repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort

-   repo: https://github.com/hakancelikdev/unimport
    rev: 0.8.4
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
